# MongoDB Atlas connection (replace <db_password> with your password)
spring.data.mongodb.uri=mongodb+srv://sharmakavya_db_user:test@demo.jdwhnvo.mongodb.net/ecomdb

# App secrets - replace with strong secrets in production
app.security.jwt-secret=change_this_to_a_very_long_secret_or_set_env_VAR
app.security.jwt-expiration-ms=3600000
app.security.aes-secret=change_this_to_any_string_used_to_derive_aes_key

# Server port (optional)
server.port=8080

# Optional: pretty print JSON for debugging
spring.jackson.serialization.indent_output=true
